spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost/ms_authors?createDatabaseIfNotExist=true&useSSL=false
  application:
    name: authors
  cloud:
    stream:
      bindings:
        authors:
          content-type: application/json
server:
  port: 0
  
---
spring:
  profiles: qa
  
